### ISSUE TITLE
websocket close after event loop ends

### ISSUE THREAD

**Issue by alexhsamuel** [apsis-scheduler/apsis#33]
```
17:30:06.408 asyncio                  [E] Task was destroyed but it is pending!
task: <Task pending coro=<websocket_log() running at /Users/alex/dev/apsis/python/apsis/service/main.py:82> wait_for=<Future finished result=None> cb=[<TaskWakeupMethWrapper object at 0x11c1d1948>()]>
17:30:06.408 asyncio                  [E] Task was destroyed but it is pending!
task: <Task pending coro=<Sanic.handle_request() running at /Users/alex/sw/conda/envs/apsis/lib/python3.6/site-packages/sanic/app.py:556> wait_for=<Task pending coro=<websocket_log() done, defined at /Users/alex/dev/apsis/python/apsis/service/main.py:77> wait_for=<Future finished result=None> cb=[<TaskWakeupMethWrapper object at 0x11c1d1948>()]>>
17:30:06.410 asyncio                  [E] Task was destroyed but it is pending!
task: <Task pending coro=<WebSocketCommonProtocol.transfer_data() running at /Users/alex/sw/conda/envs/apsis/lib/python3.6/site-packages/websockets/protocol.py:530> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x11c1d1fd8>()]> cb=[<TaskWakeupMethWrapper object at 0x11c1d1bb8>()]>
17:30:06.410 asyncio                  [E] Task was destroyed but it is pending!
task: <Task pending coro=<WebSocketCommonProtocol.close_connection() running at /Users/alex/sw/conda/envs/apsis/lib/python3.6/site-packages/websockets/protocol.py:807> wait_for=<Task pending coro=<WebSocketCommonProtocol.transfer_data() running at /Users/alex/sw/conda/envs/apsis/lib/python3.6/site-packages/websockets/protocol.py:530> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x11c1d1fd8>()]> cb=[<TaskWakeupMethWrapper object at 0x11c1d1bb8>()]>>
Exception ignored in: <generator object WebSocketCommonProtocol.close_connection at 0x11b276db0>
Traceback (most recent call last):
  File "/Users/alex/sw/conda/envs/apsis/lib/python3.6/site-packages/websockets/protocol.py", line 855, in close_connection
  File "/Users/alex/sw/conda/envs/apsis/lib/python3.6/asyncio/streams.py", line 312, in close
  File "/Users/alex/sw/conda/envs/apsis/lib/python3.6/asyncio/selector_events.py", line 621, in close
  File "/Users/alex/sw/conda/envs/apsis/lib/python3.6/asyncio/base_events.py", line 575, in call_soon
  File "/Users/alex/sw/conda/envs/apsis/lib/python3.6/asyncio/base_events.py", line 358, in _check_closed
RuntimeError: Event loop is closed
```

**Comment by alexhsamuel** [comment]
Fixed, I think.
