### ISSUE TITLE
"apsis runs" fails

### ISSUE THREAD

**Issue by alexhsamuel** [apsis-scheduler/apsis#70]
```
$ apsis runs
Error: unknown error [API status: 500]
```
```
18:11:41.836 root                     [E] Traceback (most recent call last):
  File "/home/alex/sw/conda/envs/apsis/lib/python3.7/site-packages/sanic/app.py", line 603, in handle_request
    response = await response
  File "/home/alex/dev/apsis/python/apsis/service/api.py", line 416, in runs
    until   =until,
TypeError: query() got an unexpected keyword argument 'until'
```

**Comment by alexhsamuel** [comment]
Fixed.
