### ISSUE TITLE
condition bug

### ISSUE THREAD

**Issue by alexhsamuel** [apsis-scheduler/apsis#94]
`program: $HOME/dev/apsis/jobs/test/test0 'Hello, world!'`

```
Traceback (most recent call last):
  File "/home/alex/dev/apsis/python/apsis/apsis.py", line 251, in __prepare_run
    run.actions = [ a.bind(run, self.jobs) for a in job.actions ]
  File "/home/alex/dev/apsis/python/apsis/apsis.py", line 251, in 
    run.actions = [ a.bind(run, self.jobs) for a in job.actions ]
  File "/home/alex/dev/apsis/python/apsis/actions.py", line 94, in bind
    condition = self.condition.bind(run, jobs)
AttributeError: 'Condition' object has no attribute 'bind'
```

**Comment by alexhsamuel** [comment]
No longer present.
